image: node:16-alpine3.15

definitions:
  steps:
    - step: &set-dev-env
        name: Set Dev Environment
        script:
          - echo ENV=dev >> set_env.sh
          - echo **********
          - echo **********
          - echo **********
          - echo **********
          - echo **********
        artifacts:
              **********
    - step: &set-test-env
        name: Set Test Environment
        script:
          - echo ENV=test >> set_env.sh
          - echo **********
          - echo **********
          - echo **********
          - echo **********
          - echo **********
        artifacts:
          - set_env.sh

    - step: &set-prod-env
        name: Set Prod Environment
        script:
          - echo ENV=prod >> set_env.sh
          - echo **********
          - echo **********
          - echo **********
          - echo **********
          - echo **********
        artifacts:
          - **********

    - step: &deploy
        script:
          - set -a
          - source set_env.sh
          - npm install --location=global aws-cdk
          - apk add --no-cache python3 py-pip
          - pip3 install -r requirements.txt --user
          - cdk deploy --require-approval=never

pipelines:
  branches:
    develop:
      - step: *set-dev-env
      - step:
          <<: *deploy
          name: Deploy to Dev
          trigger: manual
    staging:
      - step: *set-test-env
      - step:
          <<: *deploy
          name: Deploy to Test
          trigger: manual
    master:
      - step: *set-prod-env
      - step: 
          <<: *deploy
          name: Deploy to Prod
          trigger: manual
